In [ ]:
import nltk
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

# Sample data
documents = ["I love programming", "Programming is fun", "I love fun programming"]

# Preprocess text (optional)
nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('english')
# print(stopwords)
vectorizer = CountVectorizer(stop_words=stopwords)
# print(vectorizer)
# # Fit and transform the data into the bag-of-words model
X_bow = vectorizer.fit_transform(documents)
# print(X_bow)
# # Convert to an array and normalize (divide by total word count)
X_bow_normalized = X_bow.toarray() / X_bow.toarray().sum(axis=1, keepdims=True)
# print(X_bow_normalized)
# # Print the Bag of Words (raw counts)
print("BoW (Raw Counts):\n", X_bow.toarray())

# # Print the Bag of Words (Normalized Counts)
print("\nBoW (Normalized Counts):\n", X_bow_normalized)


BoW (Raw Counts):
 [[0 1 1]
 [1 0 1]
 [1 1 1]]

BoW (Normalized Counts):
 [[0.         0.5        0.5       ]
 [0.5        0.         0.5       ]
 [0.33333333 0.33333333 0.33333333]]


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize the TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words=stopwords)

# Fit and transform the documents
X_tfidf = tfidf_vectorizer.fit_transform(documents)

# Convert to an array and print the result
X_tfidf_array = X_tfidf.toarray()
print("\nTF-IDF:\n", X_tfidf_array)



TF-IDF:
 [[0.         0.78980693 0.61335554]
 [0.78980693 0.         0.61335554]
 [0.61980538 0.61980538 0.48133417]]


In [ ]:
!pip install nltk==3.8.1

import nltk
nltk.download('punkt')

from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize

# Tokenize the documents
tokenized_docs = [word_tokenize(doc.lower()) for doc in documents]

# Train Word2Vec model using the skip-gram approach
model = Word2Vec(tokenized_docs, vector_size=100, window=5, min_count=1, sg=1)

# Get the word embeddings for a word
word_embedding = model.wv['programming']
print("\nWord2Vec embedding for 'programming':\n", word_embedding)

# To get embeddings for all words
word_embeddings = {word: model.wv[word] for word in model.wv.index_to_key}
print("\nAll word embeddings:\n", word_embeddings)


Word2Vec embedding for 'programming':
 [-5.3622725e-04  2.3643136e-04  5.1033497e-03  9.0092728e-03
 -9.3029495e-03 -7.1168090e-03  6.4588725e-03  8.9729885e-03
 -5.0154282e-03 -3.7633716e-03  7.3805046e-03 -1.5334714e-03
 -4.5366134e-03  6.5540518e-03 -4.8601604e-03 -1.8160177e-03
  2.8765798e-03  9.9187379e-04 -8.2852151e-03 -9.4488179e-03
  7.3117660e-03  5.0702621e-03  6.7576934e-03  7.6286553e-04
  6.3508903e-03 -3.4053659e-03 -9.4640139e-04  5.7685734e-03
 -7.5216377e-03 -3.9361035e-03 -7.5115822e-03 -9.3004224e-04
  9.5381187e-03 -7.3191668e-03 -2.3337686e-03 -1.9377411e-03
  8.0774371e-03 -5.9308959e-03  4.5162440e-05 -4.7537340e-03
 -9.6035507e-03  5.0072931e-03 -8.7595852e-03 -4.3918253e-03
 -3.5099984e-05 -2.9618145e-04 -7.6612402e-03  9.6147433e-03
  4.9820580e-03  9.2331432e-03 -8.1579173e-03  4.4957981e-03
 -4.1370760e-03  8.2453608e-04  8.4986202e-03 -4.4621765e-03
  4.5175003e-03 -6.7869602e-03 -3.5484887e-03  9.3985079e-03
 -1.5776526e-03  3.2137157e-04 -4.1406299e-03

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
